### ISSUE TITLE
Inconsistent chain naming in `Lc2ppiK.json`

### ISSUE THREAD

**Issue by redeboer** [RUB-EP1/amplitude-serialization#21]
In the `Lc2ppiK.json` example, the `name`s in the `chains` sometimes have brackets and sometimes don't.

https://github.com/RUB-EP1/amplitude-serialization/blob/9fcd26e8c7cd487d93f902529c5513c977e03e62/Lc2ppiK.json#L62

https://github.com/RUB-EP1/amplitude-serialization/blob/9fcd26e8c7cd487d93f902529c5513c977e03e62/Lc2ppiK.json#L413

https://github.com/RUB-EP1/amplitude-serialization/blob/9fcd26e8c7cd487d93f902529c5513c977e03e62/Lc2ppiK.json#L602

**Comment by mmikhasenko** [comment]
Rather inconsistency than a bug: the name is an arbitrary string, in principle.
However, Karsten told me that python/c++ does not like brackets in strings

**Comment by redeboer** [comment]
> However, Karsten told me that python/c++ does not like brackets in strings

Depends what you do with the string I suppose 😅 But that goes for any language
