### ISSUE TITLE
Serialize lineshape functions

### ISSUE THREAD

**Issue by redeboer** [RUB-EP1/amplitude-serialization#22]
The section `functions` defines the lineshapes that should be inserted into `parametrization` of the propagators. Example:

https://github.com/RUB-EP1/amplitude-serialization/blob/9fcd26e8c7cd487d93f902529c5513c977e03e62/Lc2ppiK.json#L42

https://github.com/RUB-EP1/amplitude-serialization/blob/9fcd26e8c7cd487d93f902529c5513c977e03e62/Lc2ppiK.json#L756-L776

Currently, the format specifications do not yet include an exact definition of the function tree, only a `type` description (here: `BreitWigner`). Some solution ideas:

- Define the full mathematical operations in JSON format in the model file under `functions`.
  **Disadvantage**: the JSON file might become very large (human-readable?).
  **Advantage**: all information is contained within a single file.
- Provide an extra file with lineshape definitions.
  **Advantage**: smaller model JSON file and option to use a more common format like MathML (XML-based)
  **Disadvantage**: the model definition becomes split over multiple files

In either case, we preferably serialize to a common [mathematical markup language](https://en.wikipedia.org/wiki/Mathematical_markup_language). Afaics, for JSON, there is only [MathJSON](https://cortexjs.io/math-json), which is not widely adopted. [OpenMath](https://openmath.org) and [MathML](https://developer.mozilla.org/en-US/docs/Web/MathML) are more widely adopted (especially in web applications), but use XML, which is hard to read. But then again, lineshape expressions can be large and JSON won't be pretty either.

**Comment by redeboer** [comment]
Note: HS3 specifications probably won't help us here yet, because complex-valued functions are not supported.

**Comment by mmikhasenko** [comment]
I see great benefits in defining all functions fully in the format, there are cons as well. It would make it possible for different files to have different "BreitWigner"s, which is something I would not want.

I see that it might be challenging to convince the community to stick with a single definition of the BW. But it would be nice.
For now, I would like to try that, i.e. treat all non-standard parametrization as exceptions

**Comment by mmikhasenko** [comment]
Btw, there is already a way to code simple functions in HS3. They are strings.

**Comment by mmikhasenko** [comment]
It seems to me that some key functions will remain only documented in the pdf file, not in JSON.
For most of the lineshapes, I think we find that either they are cases of generic functions like `MultchannelBW`, or `PvectorKmatrix`, or provided in a text string like a few incorporated in #59 for compass.
