### ISSUE TITLE
Decay product mass definitions in (Bugg) Breit-Wigner

### ISSUE THREAD

**Issue by redeboer** [RUB-EP1/amplitude-serialization#32]
A Breit-Wigner lists the mass values of the decay products (`ma` and `mb`), while a `BreitWignerWidthExpLikeBugg` doesn't. Is this intended?

https://github.com/RUB-EP1/amplitude-serialization/blob/ecee71af8f77bc0360b3c5d8bc85592802652eb0/models/Lc2ppiK.json#L857-L863

https://github.com/RUB-EP1/amplitude-serialization/blob/ecee71af8f77bc0360b3c5d8bc85592802652eb0/models/Lc2ppiK.json#L871-L880

Of course, I can fetch `ma` and `mb` looking at the `node` of the `propagator` and then final state definition, but why is it not required to do so for the Breit-Wigner?

https://github.com/RUB-EP1/amplitude-serialization/blob/ecee71af8f77bc0360b3c5d8bc85592802652eb0/models/Lc2ppiK.json#L524-L530

https://github.com/RUB-EP1/amplitude-serialization/blob/ecee71af8f77bc0360b3c5d8bc85592802652eb0/models/Lc2ppiK.json#L14-L33

**Comment by mmikhasenko** [comment]
`BreitWignerWidthExpLikeBugg ` is a new pdf.
It lists only parameter that the functions expects. There is no relation to the `BreitWigner` formally.

> Of course, I can fetch ma and mb looking at the node of the propagator and then final state definition,

that would not be correct. `ma` and `mb` are not necessarily the decay products here. For BW, the `ma` and `mb` are used in the denominator. The masses of the decay products for the studied reaction enter the break-up momenta in the numerator.

**Comment by redeboer** [comment]
Ah I see now, I'm following [this definition](https://compwa.github.io/polarimetry/appendix/dynamics.html#bugg-breit-wigner), where indeed the `ma` and `mb` have a different meaning.

```math
\begin{array}{rcl}
  \mathcal{R}^\mathrm{Bugg}\left(m_{K\pi}^{2}\right) &=& \frac{1}{- \frac{i \Gamma_{0} m_{0} \left(m_{K\pi}^{2} - s_{A}\right) e^{- \gamma m_{K\pi}^{2}}}{m_{0}^{2} - s_{A}} + m_{0}^{2} - m_{K\pi}^{2}} \\
  s_{A} &=& m_{K}^{2} - \frac{m_{\pi}^{2}}{2} \\
  p_{m_{K},m_{\pi}}\left(m_{K\pi}^{2}\right) &=& \frac{\sqrt{\lambda\left(m_{K\pi}^{2}, m_{K}^{2}, m_{\pi}^{2}\right)}}{2 \sqrt{m_{K\pi}^{2}}} \\
\end{array}
```

But that means `ma` and `mb` are currently missing from `BreitWignerWidthExpLikeBugg` definitions?

**Comment by mmikhasenko** [comment]
`s_a` is just a numerical value.

**Comment by mmikhasenko** [comment]
Yes having sA as a parameter would make sense to me.
But as you say, we do not have to agree on it now as any rate.

**Comment by redeboer** [comment]
I think we can close this issue if you think `Lc2ppiK.json` provides enough info to construct a `BreitWignerWidthExpLikeBugg`. Otherwise, `s_a` has to be computed and added to the file and we can close the issue.

**Comment by mmikhasenko** [comment]
Yes, I'd used `s_a` as a parameter, not masses.
I coded text version of this function as a test in `ThreeBodyDecaysIO.jl`

https://github.com/mmikhasenko/ThreeBodyDecaysIO.jl/blob/main/test/test_generic.jl#L20-L37
