### ISSUE TITLE
Incorporate HS3 fields

### ISSUE THREAD

**Issue by mmikhasenko** [RUB-EP1/amplitude-serialization#5]
Compact high-level view to the format

![image](https://github.com/RUB-EP1/AmplitudeModelSerialization/assets/22725744/fb1bf122-5d7c-4f4e-bac1-62d90610830f)

**Comment by mmikhasenko** [comment]
Might be completed already

**Comment by mmikhasenko** [comment]
Just notices the `metadata` field here. That is what we are going to use, then!

**Comment by redeboer** [comment]
Nice!
Yeah I was wondering about some versioning for the schema as well. Makes sense to put that in metadata as well then. And indeed to make it a required field

**Comment by mmikhasenko** [comment]
seems resolved
