### ISSUE TITLE
Better naming for model `json` (and `qmd`) files

### ISSUE THREAD

**Issue by mmikhasenko** [RUB-EP1/amplitude-serialization#50]
One option would be

`DECAY_COLLABORATION_INSPIRE`
where the decay descriptor uses 2 for ->, e.g. `pi1+2pi+pi-pi-`.

**Comment by redeboer** [comment]
Keep in mind that the filenames translate to a page url. They are conventionally lowercase, hyphened, descriptive, and short.

If you go for scalability, I would just stick with the Inspire ID.

**Comment by redeboer** [comment]
Ah okay I thought you meant the inspire-hep citation key, but with the ID (as you wrote) would be quite clean indeed
