### ISSUE TITLE
minor: `.prettierignore` is not functional

### ISSUE THREAD

**Issue by mmikhasenko** [RUB-EP1/amplitude-serialization#80]
Just wasted two hours trying to understand `prettier` errors. It's just unintuitive.

Meanwhile, realized that our ignore file with `*.ipynn` won't work (checked it with `test.ipynb`) 
https://github.com/RUB-EP1/amplitude-serialization/blob/main/.prettierignore

It seems that to ignore all notebooks, one has to write `**/.ipynb`
https://prettier.io/docs/en/ignore

**Comment by redeboer** [comment]
Sorry to hear :( Strange that they write "`.prettierignore` uses [gitignore syntax](https://git-scm.com/docs/gitignore#_pattern_format)", in which case `*.ipynb` should be fine... Anyway, #81 fixes this.

**Comment by redeboer** [comment]
> Just wasted two hours trying to understand prettier errors. It's just unintuitive.

We may want to switch to [Biome](https://biomejs.dev), one of the many upcoming Rust-based formatters that is faster than (in this case) Prettier.
